---
apiVersion: v1
kind: Namespace
metadata:
  name: consul
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: consul
  namespace: consul
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: myconsul
  namespace: consul
spec:
  interval: 30m
  chart:
    spec:
      chart: consul
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: consul
        namespace: consul
      interval: 12h
  values:
    global:
      enabled: true
      logLevel: "info" # debug, warn, error
      datacenter: dc1
    dns:
      enabled: true
      type: ClusterIP
      clusterIP: null # 192.168.1.91
    ingress:
      enabled: true
      hosts:
        - host: consul.service.consul
          paths:
            - /
    syncCatalog:
      enabled: true
    server:
      enabled: true
      storage: 10Gi